### ISSUE TITLE
python-pcapy -> pcapy-ng support

### ISSUE THREAD

**Issue by MikhailKasimov** [jlnavarroadam/rpi-navarrux#1]
Hello!

Proposing to change ```python-pcapy``` for ```pcapy-ng``` instead: https://github.com/jlnavarroadam/rpi-navarrux/blob/master/InstalacionRPI.sh#L49

Reason: Maltrail (https://github.com/jlnavarroadam/rpi-navarrux/blob/master/InstalacionRPI.sh#L108) had nasty OOM problem on *BSD-line with ```python-pcapy``` (https://github.com/stamparm/maltrail/issues?q=is%3Aissue+is%3Aclosed+label%3Apcapy-ng-related) and, while  ```python-pcapy``` module became unmaintained by its developers, fork to ```pcapy-ng``` was done to provide Maltrail's work on Python 3.10 and to fix OOM problem. So, installation of ```python-pcapy``` via ```sudo pip3 install pcapy-ng``` command has replaced the ```apt install python-pcapy``` command.

Thank you!

**Comment by jlnavarroadam** [comment]
Mikhail, thank you very much. I update this project with your proposal.

=:)
